services:
  wachio:
    build: .
    container_name: wachio
    restart: unless-stopped
    volumes:
      - ./run.php:/app/run.php
      - ./schedule.php:/app/schedule.php
      - ./schedule.example.php:/app/schedule.example.php
    environment:
      - RACHIO_TOKEN=${RACHIO_TOKEN:-your-rachio-api-key-here}
